/**
 * React Starter Kit (https://github.com/xuanhoa88/rapid-rsk/)
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.txt file in the root directory of this source tree.
 */

import path from 'path';
import webpack from 'webpack';
import { merge } from 'webpack-merge';
import nodeExternals from 'webpack-node-externals';
import config from '../config';
import baseConfig, {
  createCSSRule,
  isDebug,
  reStyle,
  verboseConfig,
} from './baseConfig.webpack';
import { createDotenvDefinitions } from './dotenvPlugin.webpack';

/**
 * Get the compiled server entry path from webpack output configuration
 * This ensures consistent path resolution across all build tools
 * @returns {string} Absolute path to the compiled server entry (without .js extension)
 */
// Matches the output configuration below:
// output.path: config.BUILD_DIR
// output.filename: '[name].js'
// entry.server: [...]
// Result: build/server.js (require without extension)
export const SERVER_BUNDLE_PATH = path.join(config.BUILD_DIR, 'server');

/**
 * Configuration for the server-side bundle (server.js)
 * Targets Node.js environment with CommonJS output
 */
export default merge(baseConfig, {
  name: 'server',
  target: 'node',

  entry: {
    server: [path.join(config.APP_DIR, 'server.js')],
  },

  output: {
    path: config.BUILD_DIR,
    filename: '[name].js',
    chunkFilename: 'chunks/[name].js',
    libraryTarget: 'commonjs2',
  },

  // Externalize node_modules (simple and robust with webpack-node-externals)
  // Bundle CSS files (they need webpack loaders)
  externals: [
    './loadable-stats.json', // Generated by client build (@loadable/webpack-plugin)
    nodeExternals({
      allowlist: [
        reStyle, // CSS files must be bundled (need css-loader for class names)
      ],
    }),
  ],

  module: {
    rules: [
      // CSS handling for server bundle (exports class names only for SSR)
      createCSSRule({
        isClient: false,
        isDebug,
      }),
    ],
  },

  plugins: [
    // Define free variables
    // https://webpack.js.org/plugins/define-plugin/
    new webpack.DefinePlugin({
      'process.env.BROWSER': false,
      __DEV__: isDebug,
      // Inject RSK_ prefixed environment variables
      ...createDotenvDefinitions({
        prefix: 'RSK_',
        verbose: verboseConfig.isVerbose,
      }),
    }),

    // Add source-map-support to the entry file for better stack traces
    // https://webpack.js.org/plugins/banner-plugin/
    new webpack.BannerPlugin({
      banner: 'require("source-map-support").install();',
      raw: true,
      entryOnly: true, // Only add to entry file, not code-split chunks
    }),
  ],

  // Do not replace node globals with polyfills
  // https://webpack.js.org/configuration/node/
  // In webpack 5, only __dirname, __filename, and global are valid
  node: {
    __dirname: false,
    __filename: false,
    global: false,
  },
});
